/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import model.dao.ContaDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.bean.Deposito;
import model.bean.Saque;
import model.bean.Transferencia;



/**
 *
 * @author Dell
 */
public class TelaLogin extends javax.swing.JFrame{

    //MÁSCARA MONETÁRIA

//     MaskFormatter mf = new MaskFormatter("#,0.00");
     
    
    //VARIÁVEIS GLOBAIS
    double valorSaque;
    double valorDeposito;

    public TelaLogin() {
        
        initComponents();
        
        InsereJTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProot = new javax.swing.JPanel();
        jPacesso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        jPFsenha = new javax.swing.JPasswordField();
        jBentrar = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jPMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jBsaque = new javax.swing.JButton();
        jBextrato = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jBsaldo = new javax.swing.JButton();
        jBdeposito = new javax.swing.JButton();
        jBtransferencia = new javax.swing.JButton();
        jLnome = new javax.swing.JLabel();
        jLbemVindo = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        jPsaque = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jB20 = new javax.swing.JButton();
        jB50 = new javax.swing.JButton();
        jB100 = new javax.swing.JButton();
        jB200 = new javax.swing.JButton();
        jB500 = new javax.swing.JButton();
        jB1000 = new javax.swing.JButton();
        jBcancelaSaque = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        jPconfirmaSaque = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPFconfirmaSenhaSaque = new javax.swing.JPasswordField();
        jBconfirmaSenhaSaque = new javax.swing.JButton();
        jBcancelaConfirmaSaque = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        jPdeposito = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPFconfirmaSenhaDeposito = new javax.swing.JPasswordField();
        jBconfirmaSenhaDeposito = new javax.swing.JButton();
        jBcancelaDeposito = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtValorDeposito = new javax.swing.JFormattedTextField();
        background5 = new javax.swing.JLabel();
        jPsaldo = new javax.swing.JPanel();
        jBvoltar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLvalorSaldoLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        background8 = new javax.swing.JLabel();
        jPtransferencia = new javax.swing.JPanel();
        jPFconfirmaSenhaTransferencia = new javax.swing.JPasswordField();
        jBcancelaTransferencia = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBconfirmaTransferencia1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtContaAlvo = new javax.swing.JTextField();
        txtValorTransferencia = new javax.swing.JFormattedTextField();
        background6 = new javax.swing.JLabel();
        jPextrato = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jBvoltar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabelaExtrato = new javax.swing.JTable();
        background9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jProot.setLayout(new java.awt.CardLayout());

        jPacesso.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acesso");
        jPacesso.add(jLabel2);
        jLabel2.setBounds(360, 100, 70, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N° Conta");
        jPacesso.add(jLabel4);
        jLabel4.setBounds(290, 200, 70, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agência");
        jPacesso.add(jLabel3);
        jLabel3.setBounds(290, 240, 60, 23);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");
        jPacesso.add(jLabel1);
        jLabel1.setBounds(290, 280, 50, 23);

        txtNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroContaActionPerformed(evt);
            }
        });
        txtNumeroConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroContaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroContaKeyTyped(evt);
            }
        });
        jPacesso.add(txtNumeroConta);
        txtNumeroConta.setBounds(400, 200, 130, 30);

        txtAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgenciaActionPerformed(evt);
            }
        });
        txtAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgenciaKeyTyped(evt);
            }
        });
        jPacesso.add(txtAgencia);
        txtAgencia.setBounds(400, 240, 130, 30);

        jPFsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFsenhaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFsenhaKeyTyped(evt);
            }
        });
        jPacesso.add(jPFsenha);
        jPFsenha.setBounds(400, 280, 130, 30);

        jBentrar.setBackground(new java.awt.Color(255, 153, 0));
        jBentrar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBentrar.setForeground(new java.awt.Color(255, 255, 255));
        jBentrar.setText("Entrar");
        jBentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBentrarActionPerformed(evt);
            }
        });
        jPacesso.add(jBentrar);
        jBentrar.setBounds(290, 340, 240, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background.setText("jLabel2");
        jPacesso.add(background);
        background.setBounds(0, 0, 820, 540);

        jProot.add(jPacesso, "jPacesso");

        jPMenu.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecione uma opção");
        jPMenu.add(jLabel5);
        jLabel5.setBounds(300, 150, 220, 20);

        jBsaque.setBackground(new java.awt.Color(255, 153, 0));
        jBsaque.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBsaque.setForeground(new java.awt.Color(255, 255, 255));
        jBsaque.setText("Saque");
        jBsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaqueActionPerformed(evt);
            }
        });
        jPMenu.add(jBsaque);
        jBsaque.setBounds(20, 210, 270, 80);

        jBextrato.setBackground(new java.awt.Color(255, 153, 0));
        jBextrato.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBextrato.setForeground(new java.awt.Color(255, 255, 255));
        jBextrato.setText("Extrato");
        jBextrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBextratoActionPerformed(evt);
            }
        });
        jPMenu.add(jBextrato);
        jBextrato.setBounds(520, 300, 270, 80);

        jBsair.setBackground(new java.awt.Color(255, 153, 0));
        jBsair.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBsair.setForeground(new java.awt.Color(255, 255, 255));
        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        jPMenu.add(jBsair);
        jBsair.setBounds(520, 390, 270, 80);

        jBsaldo.setBackground(new java.awt.Color(255, 153, 0));
        jBsaldo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBsaldo.setForeground(new java.awt.Color(255, 255, 255));
        jBsaldo.setText("Saldo");
        jBsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaldoActionPerformed(evt);
            }
        });
        jPMenu.add(jBsaldo);
        jBsaldo.setBounds(520, 210, 270, 80);

        jBdeposito.setBackground(new java.awt.Color(255, 153, 0));
        jBdeposito.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBdeposito.setForeground(new java.awt.Color(255, 255, 255));
        jBdeposito.setText("Depósito");
        jBdeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdepositoActionPerformed(evt);
            }
        });
        jPMenu.add(jBdeposito);
        jBdeposito.setBounds(20, 300, 270, 80);

        jBtransferencia.setBackground(new java.awt.Color(255, 153, 0));
        jBtransferencia.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBtransferencia.setForeground(new java.awt.Color(255, 255, 255));
        jBtransferencia.setText("Transferência");
        jBtransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtransferenciaActionPerformed(evt);
            }
        });
        jPMenu.add(jBtransferencia);
        jBtransferencia.setBounds(20, 390, 270, 80);

        jLnome.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLnome.setForeground(new java.awt.Color(255, 255, 255));
        jLnome.setText("Nome");
        jPMenu.add(jLnome);
        jLnome.setBounds(440, 70, 60, 30);

        jLbemVindo.setBackground(new java.awt.Color(255, 255, 255));
        jLbemVindo.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLbemVindo.setForeground(new java.awt.Color(255, 255, 0));
        jLbemVindo.setText("Bem vindo(a)");
        jPMenu.add(jLbemVindo);
        jLbemVindo.setBounds(310, 70, 130, 30);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background2.setText("jLabel6");
        jPMenu.add(background2);
        background2.setBounds(-6, 0, 820, 550);

        jProot.add(jPMenu, "jPMenu");

        jPsaque.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("SAQUE");
        jPsaque.add(jLabel11);
        jLabel11.setBounds(370, 80, 70, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Selecione um valor");
        jPsaque.add(jLabel7);
        jLabel7.setBounds(310, 150, 190, 20);

        jB20.setBackground(new java.awt.Color(255, 153, 0));
        jB20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB20.setForeground(new java.awt.Color(255, 255, 255));
        jB20.setText("20");
        jB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB20ActionPerformed(evt);
            }
        });
        jPsaque.add(jB20);
        jB20.setBounds(20, 210, 270, 70);

        jB50.setBackground(new java.awt.Color(255, 153, 0));
        jB50.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB50.setForeground(new java.awt.Color(255, 255, 255));
        jB50.setText("50");
        jB50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB50ActionPerformed(evt);
            }
        });
        jPsaque.add(jB50);
        jB50.setBounds(20, 290, 270, 70);

        jB100.setBackground(new java.awt.Color(255, 153, 0));
        jB100.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB100.setForeground(new java.awt.Color(255, 255, 255));
        jB100.setText("100");
        jB100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB100ActionPerformed(evt);
            }
        });
        jPsaque.add(jB100);
        jB100.setBounds(20, 370, 270, 70);

        jB200.setBackground(new java.awt.Color(255, 153, 0));
        jB200.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB200.setForeground(new java.awt.Color(255, 255, 255));
        jB200.setText("200");
        jB200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB200ActionPerformed(evt);
            }
        });
        jPsaque.add(jB200);
        jB200.setBounds(520, 210, 270, 70);

        jB500.setBackground(new java.awt.Color(255, 153, 0));
        jB500.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB500.setForeground(new java.awt.Color(255, 255, 255));
        jB500.setText("500");
        jB500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB500ActionPerformed(evt);
            }
        });
        jPsaque.add(jB500);
        jB500.setBounds(520, 290, 270, 70);

        jB1000.setBackground(new java.awt.Color(255, 153, 0));
        jB1000.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jB1000.setForeground(new java.awt.Color(255, 255, 255));
        jB1000.setText("1000");
        jB1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1000ActionPerformed(evt);
            }
        });
        jPsaque.add(jB1000);
        jB1000.setBounds(520, 370, 270, 70);

        jBcancelaSaque.setBackground(new java.awt.Color(255, 153, 0));
        jBcancelaSaque.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBcancelaSaque.setForeground(new java.awt.Color(255, 255, 255));
        jBcancelaSaque.setText("Cancelar");
        jBcancelaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelaSaqueActionPerformed(evt);
            }
        });
        jPsaque.add(jBcancelaSaque);
        jBcancelaSaque.setBounds(310, 450, 180, 40);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background3.setText("jLabel6");
        jPsaque.add(background3);
        background3.setBounds(-6, -6, 820, 550);

        jProot.add(jPsaque, "jPsaque");

        jPconfirmaSaque.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirme sua senha");
        jPconfirmaSaque.add(jLabel6);
        jLabel6.setBounds(300, 140, 210, 30);

        jPFconfirmaSenhaSaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFconfirmaSenhaSaqueKeyReleased(evt);
            }
        });
        jPconfirmaSaque.add(jPFconfirmaSenhaSaque);
        jPFconfirmaSenhaSaque.setBounds(290, 220, 240, 30);

        jBconfirmaSenhaSaque.setBackground(new java.awt.Color(255, 153, 0));
        jBconfirmaSenhaSaque.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBconfirmaSenhaSaque.setForeground(new java.awt.Color(255, 255, 255));
        jBconfirmaSenhaSaque.setText("Confirmar");
        jBconfirmaSenhaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmaSenhaSaqueActionPerformed(evt);
            }
        });
        jPconfirmaSaque.add(jBconfirmaSenhaSaque);
        jBconfirmaSenhaSaque.setBounds(290, 270, 240, 50);

        jBcancelaConfirmaSaque.setBackground(new java.awt.Color(255, 153, 0));
        jBcancelaConfirmaSaque.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBcancelaConfirmaSaque.setForeground(new java.awt.Color(255, 255, 255));
        jBcancelaConfirmaSaque.setText("Cancelar");
        jBcancelaConfirmaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelaConfirmaSaqueActionPerformed(evt);
            }
        });
        jPconfirmaSaque.add(jBcancelaConfirmaSaque);
        jBcancelaConfirmaSaque.setBounds(290, 330, 240, 50);

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background4.setText("jLabel8");
        jPconfirmaSaque.add(background4);
        background4.setBounds(-6, -6, 830, 550);

        jProot.add(jPconfirmaSaque, "jPconfirmaSaque");

        jPdeposito.setLayout(null);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setText("DEPÓSITO");
        jPdeposito.add(jLabel12);
        jLabel12.setBounds(340, 80, 110, 30);

        jPFconfirmaSenhaDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFconfirmaSenhaDepositoKeyReleased(evt);
            }
        });
        jPdeposito.add(jPFconfirmaSenhaDeposito);
        jPFconfirmaSenhaDeposito.setBounds(360, 280, 200, 40);

        jBconfirmaSenhaDeposito.setBackground(new java.awt.Color(255, 153, 0));
        jBconfirmaSenhaDeposito.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBconfirmaSenhaDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jBconfirmaSenhaDeposito.setText("Confirmar");
        jBconfirmaSenhaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmaSenhaDepositoActionPerformed(evt);
            }
        });
        jPdeposito.add(jBconfirmaSenhaDeposito);
        jBconfirmaSenhaDeposito.setBounds(270, 330, 290, 50);

        jBcancelaDeposito.setBackground(new java.awt.Color(255, 153, 0));
        jBcancelaDeposito.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBcancelaDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jBcancelaDeposito.setText("Cancelar");
        jBcancelaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelaDepositoActionPerformed(evt);
            }
        });
        jPdeposito.add(jBcancelaDeposito);
        jBcancelaDeposito.setBounds(270, 390, 290, 50);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informe os campos abaixo");
        jPdeposito.add(jLabel8);
        jLabel8.setBounds(260, 160, 270, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor:");
        jPdeposito.add(jLabel9);
        jLabel9.setBounds(270, 240, 50, 14);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sua senha:");
        jPdeposito.add(jLabel10);
        jLabel10.setBounds(270, 280, 82, 30);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("(Limite de R$2000,00)");
        jPdeposito.add(jLabel26);
        jLabel26.setBounds(570, 240, 130, 20);

        txtValorDeposito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValorDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDepositoKeyTyped(evt);
            }
        });
        jPdeposito.add(txtValorDeposito);
        txtValorDeposito.setBounds(360, 230, 200, 40);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background5.setText("jLabel8");
        jPdeposito.add(background5);
        background5.setBounds(-3, -3, 820, 550);

        jProot.add(jPdeposito, "jPdeposito");

        jPsaldo.setLayout(null);

        jBvoltar1.setBackground(new java.awt.Color(255, 153, 0));
        jBvoltar1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBvoltar1.setForeground(new java.awt.Color(255, 255, 255));
        jBvoltar1.setText("Voltar");
        jBvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltar1ActionPerformed(evt);
            }
        });
        jPsaldo.add(jBvoltar1);
        jBvoltar1.setBounds(250, 380, 290, 50);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 102));
        jLabel21.setText("SALDO");
        jPsaldo.add(jLabel21);
        jLabel21.setBounds(360, 80, 70, 30);

        jLvalorSaldoLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLvalorSaldoLabel.setForeground(new java.awt.Color(102, 255, 255));
        jLvalorSaldoLabel.setText("        0.00");
        jPsaldo.add(jLvalorSaldoLabel);
        jLvalorSaldoLabel.setBounds(310, 250, 210, 44);

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("O  saldo atual ");
        jPsaldo.add(jLabel23);
        jLabel23.setBounds(330, 180, 150, 30);

        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background8.setText("jLabel17");
        jPsaldo.add(background8);
        background8.setBounds(-10, -6, 830, 550);

        jProot.add(jPsaldo, "jPsaldo");

        jPtransferencia.setLayout(null);
        jPtransferencia.add(jPFconfirmaSenhaTransferencia);
        jPFconfirmaSenhaTransferencia.setBounds(360, 330, 200, 40);

        jBcancelaTransferencia.setBackground(new java.awt.Color(255, 153, 0));
        jBcancelaTransferencia.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBcancelaTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        jBcancelaTransferencia.setText("Cancelar");
        jBcancelaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelaTransferenciaActionPerformed(evt);
            }
        });
        jPtransferencia.add(jBcancelaTransferencia);
        jBcancelaTransferencia.setBounds(250, 440, 310, 50);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sua senha:");
        jPtransferencia.add(jLabel13);
        jLabel13.setBounds(250, 330, 90, 40);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Valor:");
        jPtransferencia.add(jLabel14);
        jLabel14.setBounds(250, 230, 50, 40);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Informe os campos abaixo");
        jPtransferencia.add(jLabel15);
        jLabel15.setBounds(260, 160, 270, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 102));
        jLabel16.setText("TRANSFERÊNCIA");
        jPtransferencia.add(jLabel16);
        jLabel16.setBounds(310, 80, 170, 30);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Conta alvo:");
        jPtransferencia.add(jLabel18);
        jLabel18.setBounds(250, 280, 90, 40);

        jBconfirmaTransferencia1.setBackground(new java.awt.Color(255, 153, 0));
        jBconfirmaTransferencia1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBconfirmaTransferencia1.setForeground(new java.awt.Color(255, 255, 255));
        jBconfirmaTransferencia1.setText("Confirmar");
        jBconfirmaTransferencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmaTransferencia1ActionPerformed(evt);
            }
        });
        jPtransferencia.add(jBconfirmaTransferencia1);
        jBconfirmaTransferencia1.setBounds(250, 380, 310, 50);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("(Limite de R$1000,00)");
        jPtransferencia.add(jLabel20);
        jLabel20.setBounds(570, 240, 130, 17);
        jPtransferencia.add(txtContaAlvo);
        txtContaAlvo.setBounds(360, 280, 200, 40);

        txtValorTransferencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValorTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorTransferenciaKeyTyped(evt);
            }
        });
        jPtransferencia.add(txtValorTransferencia);
        txtValorTransferencia.setBounds(360, 230, 200, 40);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background6.setText("jLabel13");
        jPtransferencia.add(background6);
        background6.setBounds(0, -6, 820, 550);

        jProot.add(jPtransferencia, "jPtransferencia");

        jPextrato.setLayout(null);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 102));
        jLabel24.setText("Extrato");
        jPextrato.add(jLabel24);
        jLabel24.setBounds(360, 80, 80, 30);

        jBvoltar2.setBackground(new java.awt.Color(255, 153, 0));
        jBvoltar2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBvoltar2.setForeground(new java.awt.Color(255, 255, 255));
        jBvoltar2.setText("Voltar");
        jBvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltar2ActionPerformed(evt);
            }
        });
        jPextrato.add(jBvoltar2);
        jBvoltar2.setBounds(250, 400, 310, 50);

        jTtabelaExtrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Transação", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTtabelaExtrato);

        jPextrato.add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 820, 280);

        background9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dark-Blue-Background-For-Free-Download.jpg"))); // NOI18N
        background9.setText("jLabel17");
        jPextrato.add(background9);
        background9.setBounds(0, -6, 820, 550);

        jProot.add(jPextrato, "jPextrato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jProot.add(jPanel1, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(818, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //MÉTODO QUE OBTEM A DATA
    
    private String getDateTime() {
	DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	Date date = new Date();
	return dateFormat.format(date);
    }
    
    private void jBcancelaConfirmaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelaConfirmaSaqueActionPerformed
        
        //VOLTA P/ O MENU PRINCIPAL
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPMenu");
        
        //APAGANDO O CAMPO
        jPFconfirmaSenhaSaque.setText("");
        
    }//GEN-LAST:event_jBcancelaConfirmaSaqueActionPerformed

    private void jBconfirmaSenhaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmaSenhaSaqueActionPerformed
         
             confirmaSaque(valorSaque);
             
            //VOLTA P/ A TELA DE ACESSO
             CardLayout cl = (CardLayout) jProot.getLayout();
             cl.show(jProot, "jPMenu");
    }//GEN-LAST:event_jBconfirmaSenhaSaqueActionPerformed

    private void jB20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB20ActionPerformed
          
        //SUBTRAI R$ 20.00 DO SALDO 
        //CHAMA TELA DE CONFIRMACAO DE SAQUE 
        //ADICIONA NO EXTRATO 
        
         valorSaque = 20.00;
                        
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
        
    }//GEN-LAST:event_jB20ActionPerformed

    private void jB50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB50ActionPerformed
       
        //SUBTRAI R$ 50.00 DO SALDO  
        //CHAMA TELA DE CONFIRMACAO DE SAQUE  
        //ADICIONA NO EXTRATO 
       
        valorSaque = 50.00;
            
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
        
    }//GEN-LAST:event_jB50ActionPerformed

    private void jB100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB100ActionPerformed
              
            //SUBTRAI R$ 100.00 DO SALDO 
            //CHAMA TELA DE CONFIRMACAO DE SAQUE
            //ADICIONA NO EXTRATO
            
            valorSaque = 100.00;
        
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
            
    }//GEN-LAST:event_jB100ActionPerformed

    private void jB200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB200ActionPerformed
               
            //SUBTRAI R$ 200.00 DO SALDO
            //CHAMA TELA DE CONFIRMACAO DE SAQUE  
            //ADICIONA NO EXTRATO
            
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            nf.format(valorSaque = 200.00);
        
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
            
    }//GEN-LAST:event_jB200ActionPerformed

    private void jBcancelaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelaSaqueActionPerformed
               
            //VOLTA P/ A TELA DE ACESSO
             CardLayout cl = (CardLayout) jProot.getLayout();
             cl.show(jProot, "jPMenu");
             
              //APAGANDO OS CAMPOS 
                jPFconfirmaSenhaSaque.setText("");
     
    }//GEN-LAST:event_jBcancelaSaqueActionPerformed

    private void jBconfirmaSenhaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmaSenhaDepositoActionPerformed

        //CONFIRMA SENHA 
        //ADICIONA O VALOR NA CONTA ATUAL
        
        //VALOR DO DEPOSITO
        double depValor = Double.parseDouble(txtValorDeposito.getText().replace(",","."));      
        confirmaDeposito(depValor);
        

        
        //APAGANDO  OS CAMPOS
        txtValorDeposito.setText("");
        jPFconfirmaSenhaDeposito.setText("");
        
        //VOLTA AO MENU DE OPERAÇÕES
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPMenu");
    }//GEN-LAST:event_jBconfirmaSenhaDepositoActionPerformed

    private void jBcancelaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelaDepositoActionPerformed
       
        //VOLTA AO MENU DE OPERAÇÕES
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPMenu");
        
        //APAGANDO OS CAMPOS
        txtValorDeposito.setText("");
        jPFconfirmaSenhaDeposito.setText("");
        
    }//GEN-LAST:event_jBcancelaDepositoActionPerformed

    private void jBcancelaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelaTransferenciaActionPerformed
        
        //VOLTA AO MENU DE OPERAÇÕES
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPMenu");
        
        //APAGANDO OS CAMPOS
        txtContaAlvo.setText("");
        txtValorTransferencia.setText("");
        jPFconfirmaSenhaTransferencia.setText("");
        
    }//GEN-LAST:event_jBcancelaTransferenciaActionPerformed

    private void jBconfirmaTransferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmaTransferencia1ActionPerformed

        String c = txtContaAlvo.getText();
        double v = Double.parseDouble(txtValorTransferencia.getText().replace(",","."));
        String s = jPFconfirmaSenhaTransferencia.getText();
                   
            
            confirmaTransferencia(c,v,s);
    
               // APAGANDO OS CAMPOS
                txtContaAlvo.setText("");
                txtValorTransferencia.setText("");
                jPFconfirmaSenhaTransferencia.setText("");

                CardLayout cl = (CardLayout) jProot.getLayout();
                cl.show(jProot, "jPMenu");
              
    }//GEN-LAST:event_jBconfirmaTransferencia1ActionPerformed

    private void jBentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBentrarActionPerformed
            
        ContaDAO dao = new ContaDAO();
        
         if(dao.conta(txtNumeroConta.getText(), txtAgencia.getText(), jPFsenha.getText())){
             
             welcome();
              
             CardLayout cl = (CardLayout) jProot.getLayout();
             cl.show(jProot, "jPMenu");
         }
         else{
             JOptionPane.showMessageDialog(null, "DIGITE OS DADOS CORRETAMENTE");
                txtNumeroConta.setText("");
                txtAgencia.setText("");
                jPFsenha.setText("");
         }
            
    }//GEN-LAST:event_jBentrarActionPerformed

    private void jBvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltar1ActionPerformed

        //VOLTANDO AO MENU DE OPERAÇÕES
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot,"jPMenu");

    }//GEN-LAST:event_jBvoltar1ActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed

        valorDeposito = 0.00;
        valorSaque = 0.00;
//        Numconta = "";
        txtNumeroConta.setText("");
        txtAgencia.setText("");
        jPFsenha.setText("");
        
        

        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPacesso");

        
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaqueActionPerformed

        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot,"jPsaque");        

    }//GEN-LAST:event_jBsaqueActionPerformed

    private void jBdepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdepositoActionPerformed

        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPdeposito");
        
    }//GEN-LAST:event_jBdepositoActionPerformed

    private void jBtransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtransferenciaActionPerformed
       
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPtransferencia");
        
    }//GEN-LAST:event_jBtransferenciaActionPerformed
             
    private void jBsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaldoActionPerformed
    
        mostraSaldo();
        
        CardLayout cl  = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPsaldo");
      
    }//GEN-LAST:event_jBsaldoActionPerformed

    private void jBvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltar2ActionPerformed

        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPMenu");
    }//GEN-LAST:event_jBvoltar2ActionPerformed

    private void jBextratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBextratoActionPerformed
            
        InsereJTable();
        
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPextrato");
        
        
    }//GEN-LAST:event_jBextratoActionPerformed


    private void txtNumeroContaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroContaKeyReleased

    }//GEN-LAST:event_txtNumeroContaKeyReleased

    private void jPFsenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFsenhaKeyReleased
        
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          
              ContaDAO dao = new ContaDAO();
        
            if(dao.conta(txtNumeroConta.getText(), txtAgencia.getText(), jPFsenha.getText())){
               
                welcome();
                
                CardLayout cl = (CardLayout) jProot.getLayout();
                cl.show(jProot, "jPMenu");
            }
            else{
                JOptionPane.showMessageDialog(null, "DIGITE OS DADOS CORRETAMENTE");
            }
            
        }
        
    }//GEN-LAST:event_jPFsenhaKeyReleased


    private void txtNumeroContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroContaKeyTyped
                
     //ACEITANDO APENAS NUMEROS COMO CARACTERES
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        

    }//GEN-LAST:event_txtNumeroContaKeyTyped

    private void txtAgenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgenciaKeyTyped
       
         //ACEITANDO APENAS NUMEROS COMO CARACTERES
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtAgenciaKeyTyped

    private void jPFsenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFsenhaKeyTyped
    
        //ACEITANDO APENAS NUMEROS COMO CARACTERES
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        
    }//GEN-LAST:event_jPFsenhaKeyTyped

    private void txtNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroContaActionPerformed

    private void txtAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgenciaActionPerformed

    private void jB1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1000ActionPerformed
        
        valorSaque = 1000.00;
       
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
    }//GEN-LAST:event_jB1000ActionPerformed

    private void jB500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB500ActionPerformed
        
        valorSaque = 500.00;
       
        CardLayout cl = (CardLayout) jProot.getLayout();
        cl.show(jProot, "jPconfirmaSaque");
        
    }//GEN-LAST:event_jB500ActionPerformed

    private void txtValorTransferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTransferenciaKeyTyped

        String caracteres="0987654321.,";
        String conteudo = txtValorTransferencia.getText().replace(",",".");
        
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        
        if(conteudo.length() >= 8){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtValorTransferenciaKeyTyped

    private void txtValorDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDepositoKeyTyped

        String caracteres="0987654321,.";
        String conteudo = txtValorDeposito.getText();//.replace(",",".");
        
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        
        if(conteudo.length() >= 8){
            evt.consume();
        }

    }//GEN-LAST:event_txtValorDepositoKeyTyped

    private void jPFconfirmaSenhaSaqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFconfirmaSenhaSaqueKeyReleased

         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         
            confirmaSaque(valorSaque);
             
            //VOLTA P/ A TELA DE ACESSO
             CardLayout cl = (CardLayout) jProot.getLayout();
             cl.show(jProot, "jPMenu");
     
         }
        
    
    }//GEN-LAST:event_jPFconfirmaSenhaSaqueKeyReleased

    private void jPFconfirmaSenhaDepositoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFconfirmaSenhaDepositoKeyReleased

         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         
            double depValor = Double.parseDouble(txtValorDeposito.getText().replace(",","."));      
            confirmaDeposito(depValor);
        
            //APAGANDO  OS CAMPOS
            txtValorDeposito.setText("");
            jPFconfirmaSenhaDeposito.setText("");

            //VOLTA AO MENU DE OPERAÇÕES
            CardLayout cl = (CardLayout) jProot.getLayout();
            cl.show(jProot, "jPMenu");
             
         }

        
    }//GEN-LAST:event_jPFconfirmaSenhaDepositoKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//          MaskFormatter mascaraReal = null;
//          try{
//              mascaraReal = new MaskFormatter("#.###,##");
//          }catch (ParseException e){ 
//          }
//          JFormattedTextField txtValorDeposito = new JFormattedTextField(mascaraReal);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
                
                
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background8;
    private javax.swing.JLabel background9;
    private javax.swing.JButton jB100;
    private javax.swing.JButton jB1000;
    private javax.swing.JButton jB20;
    private javax.swing.JButton jB200;
    private javax.swing.JButton jB50;
    private javax.swing.JButton jB500;
    private javax.swing.JButton jBcancelaConfirmaSaque;
    private javax.swing.JButton jBcancelaDeposito;
    private javax.swing.JButton jBcancelaSaque;
    private javax.swing.JButton jBcancelaTransferencia;
    private javax.swing.JButton jBconfirmaSenhaDeposito;
    private javax.swing.JButton jBconfirmaSenhaSaque;
    private javax.swing.JButton jBconfirmaTransferencia1;
    private javax.swing.JButton jBdeposito;
    private javax.swing.JButton jBentrar;
    private javax.swing.JButton jBextrato;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsaldo;
    private javax.swing.JButton jBsaque;
    private javax.swing.JButton jBtransferencia;
    private javax.swing.JButton jBvoltar1;
    private javax.swing.JButton jBvoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbemVindo;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLvalorSaldoLabel;
    private javax.swing.JPasswordField jPFconfirmaSenhaDeposito;
    private javax.swing.JPasswordField jPFconfirmaSenhaSaque;
    private javax.swing.JPasswordField jPFconfirmaSenhaTransferencia;
    private static javax.swing.JPasswordField jPFsenha;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPacesso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPconfirmaSaque;
    private javax.swing.JPanel jPdeposito;
    private javax.swing.JPanel jPextrato;
    private javax.swing.JPanel jProot;
    private javax.swing.JPanel jPsaldo;
    private javax.swing.JPanel jPsaque;
    private javax.swing.JPanel jPtransferencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTtabelaExtrato;
    private static javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtContaAlvo;
    private static javax.swing.JTextField txtNumeroConta;
    private javax.swing.JFormattedTextField txtValorDeposito;
    private javax.swing.JFormattedTextField txtValorTransferencia;
    // End of variables declaration//GEN-END:variables

    //MÉTODOS DOS SAQUES
   private void confirmaSaque(double valorSaque){ //RECEBE O VALOR DO SAQUE PARA FAZER O UPDATE
         
         String y = txtNumeroConta.getText();// CONTA
         String senha = jPFsenha.getText();//PEGANDO A SENHA
         String data = getDateTime(); //PEGANDO A DATA
         
         //MUDANDO A VARIÁVEL GLOBAL (Numconta) PARA MOSTRAR O EXTRATO
//         Numconta = y;// RECEBE O NUMERO DA CONTA DIGITADA NA TELA DE ACESSO
         
         Saque saque = new Saque();
         ContaDAO dao = new ContaDAO();   
         
         double saldo = dao.Saldo(y);//PEGANDO O VALOR DO SALDO 
         String tipoTransacao = saque.getTransacao();//PEGANDO O TIPO DA TRANSAÇAO
         
         //PEGANDO O VALOR DO SAQUE A SER MOSTRADO
         
          NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
          String valor = nf.format(valorSaque);//CONVERTENDO PARA MOSTRAR 
          //DefaultTableModel tabela = (DefaultTableModel) jTtabelaExtrato.getModel();
        
        if(saldo < valorSaque){//TESTAR ESTE TRECHO
            JOptionPane.showMessageDialog(null, "SALDO INSUFICIENTE PARA O VALOR DO SAQUE");
        }
        else if(senha.equals(jPFconfirmaSenhaSaque.getText())){
                    
                    //INSERINDO NO BANCO
                    dao.subSaldo(valorSaque, y);//PASSANDO O VALOR DO SAQUE E A CONTA.
                    dao.Saque(valorSaque, data);//""""""""""""""""""""""""""""" DATA.
                    dao.addExtrato(data, tipoTransacao, valorSaque, y);//ADICIONANDO NO EXTRATO
                    
                   

                      

                    //MOSTRANDO O VALOR NO JOptionPane
                    JOptionPane.showMessageDialog(null, "SAQUE DE " + valor +" REALIZADO COM SUCESSO");

//                     InsereLista();//INSERINDO AS INFORMAÇÕES NA TABELA DO EXTRATO(SOFTWARE).
                    
                    jPFconfirmaSenhaSaque.setText("");
                    CardLayout cl = (CardLayout) jProot.getLayout();
                    cl.show(jProot, "jPMenu");       
        }  
        else{
             
             JOptionPane.showMessageDialog(null,"SENHA INVÁLIDA" );
             jPFconfirmaSenhaSaque.setText("");
              CardLayout cl = (CardLayout) jProot.getLayout();
              cl.show(jProot, "jPMenu");
        }
         
   }
      
    private void confirmaDeposito(double valorDeposito){
      
       String x = txtNumeroConta.getText();// CONTA
       String senha = jPFsenha.getText();//SENHA
       String data = getDateTime();//DATA
       
       
        //MUDANDO A VARIÁVEL GLOBAL (Numconta) PARA MOSTRAR O EXTRATO
//         Numconta = x;// RECEBE O NUMERO DA CONTA DIGITADA NA TELA DE ACESSO
       
            
            Deposito deposito = new Deposito();
            ContaDAO dao = new ContaDAO();
            
            String tipoTransacao = deposito.getTransacao();
               
            if(senha.equals(jPFconfirmaSenhaDeposito.getText())){//SE A SENHA EXISTIR
               
                if(valorDeposito >= 2001){
                   JOptionPane.showMessageDialog(null, " VALOR LIMITE DE DEPÓSITO EXCEDIDO!\n LIMITE: (R$ 2000.00) ");
               }
                
                else{
                     
                //INSERINDO NO BANCO....
                dao.addSaldo(valorDeposito, x);
                dao.Deposito(valorDeposito, data);
                dao.addExtrato(data, tipoTransacao, valorDeposito, x);

                //PEGANDO O VALOR DO DEPÓSITO A SER MOSTRADO
                NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
                String valor = nf.format(valorDeposito);//CONVERTENDO PARA MOSTRAR 
                
                 

                //MOSTRANDO
                JOptionPane.showMessageDialog(null, "DEPÓSITO DE " + valor + " REALIZADO COM SUCESSO");
               
//                InsereLista();//INSERINDO AS INFORMAÇÕES NA TABELA DO EXTRATO(SOFTWARE).
                
                //APAGANDO OS CAMPOS
                txtValorDeposito.setText("");
                jPFconfirmaSenhaDeposito.setText("");
                
                CardLayout cl = (CardLayout) jProot.getLayout();
                cl.show(jProot, "jPMenu");
                
               }
           }
            else{

                JOptionPane.showMessageDialog(null, "SENHA INVÁLIDA");
                
               //APAGANDO OS CAMPOS
                txtValorDeposito.setText("");
                jPFconfirmaSenhaDeposito.setText("");
                
                CardLayout cl = (CardLayout) jProot.getLayout();
                cl.show(jProot, "jPMenu");

            }  
    }

    
    private void confirmaTransferencia(String contaAlvo, double valorTransferencia, String senha){
        
        String z = jPFsenha.getText();
        String data = getDateTime();
        String contaAtual = txtNumeroConta.getText();
       
        ContaDAO dao = new ContaDAO();
        boolean exts = dao.contaExists(contaAlvo);
        
        Transferencia transferencia = new Transferencia();
        String tipoTransacao = transferencia.getTransacao();
        
        if(exts && z.equals(senha)){ //SE A CONTA ALVO EXISTIR E SE A SENHA FOR CORRETA
            
            if(valorTransferencia >= 1001){ //SE O VALOR LIMITE FOR ATINGINDO....
                JOptionPane.showMessageDialog(null, " VALOR LIMITE DE TRANSFERÊNCIA ATINGIDO!\n LIMITE: (R$ 1000.00) ");
                 txtContaAlvo.setText("");
                 txtValorTransferencia.setText("");
                 jPFconfirmaSenhaTransferencia.setText("");
                 
            } else{
                 
                if(contaAlvo.equals(contaAtual)){
            
                    JOptionPane.showMessageDialog(null, " ERRO: A CONTA ALVO PRECISA SER DIFERENTE DA SUA CONTA DE ACESSO! ");
                    //APAGANDO OS CAMPOS
                    txtContaAlvo.setText("");
                    txtValorTransferencia.setText("");
                    jPFconfirmaSenhaTransferencia.setText("");
                    
                }
                else if (contaAlvo != (contaAtual)){
                
                    //INSERINDO NA CONTA ALVO
                        dao.addSaldo(valorTransferencia, contaAlvo);

                        //SUBTRAINDO DA CONTA ATUAL
                        dao.subSaldo(valorTransferencia, contaAtual);

                        //ADICIONANDO NA TABELA TRANSFERENCIA
                        dao.Transfer(contaAlvo, valorTransferencia, data);

                        //ADICIONANDO NO EXTRATO
                        dao.addExtrato(data, tipoTransacao, valorTransferencia, z);

                       //MOSTRANDO MENSAGEM DE SUCESSO
                        JOptionPane.showMessageDialog(null, "TRANSFERÊNCIA REALIZADA COM SUCESSO");
                        
                        //APAGANDO OS CAMPOS
                        txtContaAlvo.setText("");
                        txtValorTransferencia.setText("");
                        jPFconfirmaSenhaTransferencia.setText("");

                }
                
                //VOLTANDO AO MENU PRINCIPAL
                 CardLayout cl = (CardLayout) jProot.getLayout();
                 cl.show(jProot, "jPMenu");
            }
             
        }
        else{
            
        JOptionPane.showMessageDialog(null, " CONTA ALVO OU SENHA INCORRETAS! INFORME-AS CORRETAMENTE");
            
            //APAGANDO OS CAMPOS
                txtContaAlvo.setText("");
                txtValorTransferencia.setText("");
                jPFconfirmaSenhaTransferencia.setText("");
            
        }
        

    }
        
   public void mostraSaldo(){
        
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        ContaDAO dao = new ContaDAO();
        double res = dao.Saldo(txtNumeroConta.getText());
        
        String FormatSaldo = nf.format(res);        
        jLvalorSaldoLabel.setText(FormatSaldo);
   }
   
   
   
   public void welcome(){
       
       ContaDAO dao = new ContaDAO();
       String nome; 
       
       nome = dao.nome(txtNumeroConta.getText());
       
       jLbemVindo.setText("Bem vindo(a)");
       jLnome.setText(nome);
       
   }
   
       public void InsereJTable(){
        
        ContaDAO dao  = new ContaDAO();
        String conta = txtNumeroConta.getText();
        DefaultTableModel modelo = (DefaultTableModel)jTtabelaExtrato.getModel();
        
        jTtabelaExtrato.setModel(dao.extrato(modelo, conta));
         
    }
   
    
}